#!/bin/bash
# pullins - pull & install
# Last Edit: 28.05.2012

# read configuration and functions
source /etc/nsc-tools/nsc-client.conf
source /etc/nsc-tools/functions

set -o nounset

# preliminary checks
if [ "$UID" != "0" ]; then
	echo "You need to be root to use this program! Exiting..."
	exit 1
fi

if [ $# -eq 0 ]; then
    echo "You should pass the names of some packages you want to install! Exiting..."
    exit 2
fi

# handle SIGINT
trap cleanup INT

# download the packages on the server side
print_color_msg "Action on the remote cache server"
ssh $REPO_USER@$REPO_IP /home/$REPO_USER/download-pkgs "$@"

# mount the NFS share on our side and install the packages
print_color_msg "Actions taking place on this machine"
mount_share &&
print_color_msg "Starting LOCAL pacman for install..." &&
pacman --dbpath "$MOUNTPOINT/db" --cachedir "$MOUNTPOINT/cache" -S "$@"

push_pkglist_if_neccessary

cleanup
