#!/bin/bash
# pullup - pull updates
# Last Edit: 28.05.2012

# parse config here
source /etc/nsc-tools/nsc-client.conf
source /etc/nsc-tools/functions

# preliminary checks
if [ "$UID" != "0" ]; then
	echo "You need to be root to use this program! Exiting..."
	exit 1
fi

# handle interrupt signals
trap cleanup INT

# mount the share and pull the updates
print_color_msg "Actions taking place on this machine"
mount_share &&
print_color_msg "Starting LOCAL pacman for update..." &&
pacman --dbpath "$MOUNTPOINT/db" --cachedir "$MOUNTPOINT/cache" -Su

# This step is needed to handle dependencies correctly
# but only do if the update was successful
push_pkglist_if_neccessary

# remove mountpoint and the mount itself
cleanup
