#!/bin/sh
# pullup - pull updates
# v1

# script variables, parse config here
source ../config/nsc-client.conf

# preliminary checks
if [ "$UID" != "0" ]; then
	echo "You need to be root to use this program! Exiting..."
	exit 1
fi

# mount the share and pull the updates
echo "Actions taking place on this machine"
mkdir -p "$MOUNTPOINT/cache" "$MOUNTPOINT/db" && echo "Creating mountpoint..." &&
/bin/ln -s "$MOUNTPOINT/cache/db/sync" "$MOUNTPOINT/db" && echo "Symlinking remote sync db..." &&
/bin/ln -s "$LOCALDB" "$MOUNTPOINT/db" && echo "Symlinking local db..." &&
echo "Mounting remote cache..." && mount -t cifs "//$REPO_IP/$REPO_NAME" "$MOUNTPOINT/cache" -o user=none,password=none &&
echo "Updating" && pacman --dbpath "$MOUNTPOINT/db" --cachedir "$MOUNTPOINT" -Su

# unmount anyway
echo "Unmounting remote cache..." && umount "$MOUNTPOINT/cache" && 
echo "Removing mountpoint..." && rm -r "$MOUNTPOINT"
