#!/bin/bash
# remorem - remote removal of packages
# v1

# script variables, parse config here
source /etc/nsc-client.conf

# preliminary checks
if [ "$UID" != "0" ]; then
	echo "You need to be root to use this program! Exiting..."
	exit 1
fi

# Remove the packages locally
echo "Removing the packages locally..."
pacman -Rscn "$@"

# This step is needed so that package dependencies are handled correctly
# but only do it, if the remove was successful
if [ "$?" == "0" ]; then
	echo "Creating a new package list and copying it over to the server"
	comm -23 <(pacman -Qq|sort) <(pacman -Qmq|sort) > /tmp/`hostname`.pkglist
	scp /tmp/`hostname`.pkglist "$REPO_USER@$REPO_IP:$REPO_DIR/nsc"
	rm  /tmp/`hostname`.pkglist
fi
