#!/bin/sh
# remorem - remote removal of packages
# v1

# script variables, parse config here
source /etc/nsc-client.conf

# preliminary checks
if [ "$UID" != "0" ]; then
	echo "You need to be root to use this program! Exiting..."
	exit 1
fi

# download the packages on the server side
echo "Action on the remote server"
ssh $REPO_USER@$REPO_IP /home/$REPO_USER/remove-pkgs "$@" "$HOSTNAME"

# mount the NFS share on our side and install the packages
echo "Actions taking place on this machine"
pacman -Rscn "$@"
