#!/bin/bash
# remorem - remote removal of packages
# Last Edit: 27.05.2012

# script variables, parse config here
source /etc/nsc-client.conf

# preliminary checks
if [ "$UID" != "0" ]; then
	echo "You need to be root to use this program! Exiting..."
	exit 1
fi

if [ $# -eq 0 ]; then
    echo "Pass at least one package that should be removed! Exiting..."
    exit 2
fi

# Remove the packages locally
echo "Removing the packages locally..."
pacman -Rscn "$@"

# This step is needed so that package dependencies are handled correctly
# but only do it, if the remove was successful
if [ "$?" == "0" ]; then
	echo "Creating a new package list and copying it over to the server"
	comm -23 <(pacman -Qq|sort) <(pacman -Qmq|sort) > /tmp/`hostname`.pkglist
	scp /tmp/`hostname`.pkglist "$REPO_USER@$REPO_IP:nsc_dir_link"
	rm  /tmp/`hostname`.pkglist
fi
