#!/bin/sh
# download-pkgs - download packages into the remote cache
# v2

# source configuration
source ~/nsc-tools/server/config/nsc-server.conf

# the main functionality
echo "Download of $# packages requested"
echo "Starting pacman...downloading all requested files at once"
sudo pacman --noprogressbar --noconfirm --config "$REPO_DIR/nsc/pacman.conf" -Sw $@
