#!/bin/sh
# remove-pkgs - removes requested pkgs from device list
# v1

# source configuration
source ../config/nsc-server.conf

# script variables
PKGS=("$@")
CONNECTING_HOST="${PKGS[$#-1]}"
unset PKGS[$#-1]

# the functionality
echo "remove-pkg script release 1"
echo "Download of $(($#-1)) packages requested"

if [ "$CONNECTING_HOST" == "" ]; then
	echo "Could not verify request origin! Exiting..."
	exit 1
fi

echo "Starting pacman...removing each requested file piecemeal"

for PKG in ${PKGS[@]}; do
	sed "/^$PKG$/ d" "$REPO_DIR/nsc/$CONNECTING_HOST.pkglist" > "$DUMP"
	mv "$DUMP" "$REPO_DIR/nsc/$CONNECTING_HOST.pkglist"
done
